# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdui < Formula
  desc "Terminal UI for browsing your working-tree git diff as a sparse, collapsible file tree"
  homepage "https://github.com/andreas-bergstrom/gdui"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.1.0/gdui_0.1.0_darwin_amd64.tar.gz"
      sha256 "c3141b6568e13cf01408ea215d0a44c08c88358f9215c5fcb2f53c9067866262"

      define_method(:install) do
        bin.install "gdui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.1.0/gdui_0.1.0_darwin_arm64.tar.gz"
      sha256 "418015d0ed576e13f348d61bcd7fc75cce879662b7008f15c0934d28d7e1363b"

      define_method(:install) do
        bin.install "gdui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.1.0/gdui_0.1.0_linux_amd64.tar.gz"
      sha256 "36a165b9c6128d53bebbd7118c0ac4e6ad516b849d3fada295ab023c369a2278"
      define_method(:install) do
        bin.install "gdui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.1.0/gdui_0.1.0_linux_arm64.tar.gz"
      sha256 "08c24d79b16ae0c9c18a6768d7770f364985de5a89e7eb141fbb858d51e3a269"
      define_method(:install) do
        bin.install "gdui"
      end
    end
  end

  test do
    assert_match "gdui", shell_output("#{bin}/gdui --version")
  end
end
