# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdui < Formula
  desc "Terminal UI for browsing your working-tree git diff as a sparse, collapsible file tree"
  homepage "https://github.com/andreas-bergstrom/gdui"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.2.0/gdui_0.2.0_darwin_amd64.tar.gz"
      sha256 "62f799df2ce08636b82a03809520a1f80ef4e65398741b066c124a46ee24a384"

      define_method(:install) do
        bin.install "gdui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.2.0/gdui_0.2.0_darwin_arm64.tar.gz"
      sha256 "841acdb08b401a94e4155aab83b10efc5191630043fb0b43b9515504b8f6d8ab"

      define_method(:install) do
        bin.install "gdui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.2.0/gdui_0.2.0_linux_amd64.tar.gz"
      sha256 "23c393c72d1e10108bba44a97cec9556b8153ff8d540275163a3b20a56eaee1c"
      define_method(:install) do
        bin.install "gdui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andreas-bergstrom/gdui/releases/download/v0.2.0/gdui_0.2.0_linux_arm64.tar.gz"
      sha256 "72dd7e1df42bbf87a559b91a709e56ffb8119b9e95166740de9309a0ce28d0ba"
      define_method(:install) do
        bin.install "gdui"
      end
    end
  end

  test do
    assert_match "gdui", shell_output("#{bin}/gdui --version")
  end
end
